# Actions workflow

name: CI_PIPELINE

# Workflow Triggers
on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

# Workflow Jobs
jobs:
  # Test and Build Job
  build:
    # Runner Image
    runs-on: ubuntu-latest
    steps:

      # Checkout
      - name: Checkout
        uses: actions/checkout@v2

      # Python Installation
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.5'
      - name: Cache pip
        uses: actions/cache@v2
        with:
          # This path is specific to Ubuntu
          path: ~/.cache/pip
          # Look to see if there is a cache hit for the corresponding requirements file
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Setup And Test
      - name: Setup And Test
        run: |
          sed -i "s/__version__\s*=\s*\"\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\"/__version__ = \"\1.\2.$GITHUB_RUN_NUMBER\"/" veroku/__init__.py
          python -m unittest discover -s ./veroku/tests -t ./ -p 'test_*.py'

      # Package and Upload

      - name: Extract Branch Name
        run: echo "::set-env name=BRANCH::$(echo ${GITHUB_REF##*/})"
      - name: Package And Upload
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: ./actions_scripts/publish_to_pypi.sh

      # TODO: find better solution than copying actions_scripts to parent dir
      # Create and Publish Documentation
      - run: |
          cd ./docs
          sphinx-apidoc -f -e -o source/ ../veroku/ ../veroku/tests/
          make html
          cd ../
          cp -R docs ../docs_copy
          cp -R actions_scripts ../actions_scripts

      - name: Checkout Github Pages Branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - run: ../actions_scripts/publish_documentation.sh