# Actions workflow

name: CI_PIPELINE

# Workflow Triggers
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Workflow Jobs
jobs:
  # Test and Build Job
  build:
    # Runner Image
    runs-on: ubuntu-latest
    steps:
      # Check-out $GITHUB_WORKSPACE repo
      - uses: actions/checkout@v2

      # Setup and Test
      - name: SetupAndTest
        run: |
          pip install -r requirements.txt
          echo test, and deploy your project.

      # Update version number
      - name: SetupAndTest
        run: |
          echo GITHUB_RUN_ID
          echo $GITHUB_RUN_ID
          sed -i "s/__version__\s*=\s*\"\([0-9]\+\)\.\([0-9]\+\)\.\([0-9]\+\)\"/__version__ = \"\1.\2.$GITHUB_RUN_ID\"/" veroku/__init__.py
          echo "version in init:"
          head veroku/__init__.py
      # Package and Upload
      - name: SetupAndTest
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          pip install twine
          python setup.py sdist bdist_wheel
          ls -la ./dist
#         python -m twine upload --verbose -u $PYPI_USERNAME -p $PYPI_PASSWORD --repository-url https://upload.pypi.org/legacy/ dist/*

