# Actions workflow

name: CI

# Workflow Triggers
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# Workflow Jobs
jobs:
  # Test and Build Job
  build:
    # Runner Image
    runs-on: ubuntu-latest
    steps:
      # Check-out $GITHUB_WORKSPACE repo
      - uses: actions/checkout@v2

      # Setup and Test
      - name: SetupAndTest
        run: |
          pip install -r requirements
          echo test, and deploy your project.

      # Package and Upload
      - name: SetupAndTest
        run: |
          pip install twine
          python setup.py sdist bdist_wheel
#          python -m twine upload --verbose -u $PYPI_USER -p $PYPI_PASSWORD --repository-url https://upload.pypi.org/legacy/ dist/*

